/*
---------------------------------------------------------------------
NAME:24.c
AUHTOR: GANGASAGAR HL
ROLL NO: MT2024048
DESCRIPTION:Write a program to create a message queue and print the key and message queue id.
DATE: SEP 18 2024
---------------------------------------------------------------------
*/


#include<stdio.h>
#include<unistd.h>
#include<sys/ipc.h>
#include<sys/types.h>
#include<sys/msg.h>

int main(void) {
	
	int msg_queue = ftok(".", 1);
	/*
	s used to generate a unique key for inter-process communication (IPC), particularly for creating shared memory segments, message queues, and semaphores. It generates the key based on a filename and a project identifier.
	
	key_t ftok(const char *pathname, int proj_id);
	
	
	pathname: The path to an existing file, used as a reference point to generate the key.
proj_id: A project identifier, typically a character that, when combined with the file path, ensures the uniqueness of the key.

The ftok function combines the inode number of the file specified by pathname and the lower 8 bits of proj_id to generate a unique key.
The key generated by ftok is then used to create or access IPC objects like shared memory, message queues, or semaphores.
	*/
	
	if(msg_queue == -1) {
		perror("Error");
		return 0;
	}
	
	int que = msgget(msg_queue, IPC_CREAT | 0777);
	/*
	creating or accessing a message queue. Message queues allow processes to communicate with each other by sending and receiving messages.
	
	int msgget(key_t key, int msgflg);
	
	key: This is a key generated by ftok() or a specific hardcoded value used to uniquely identify the message queue.
msgflg: This specifies the flags for creating or accessing the message queue. Common flags include:
IPC_CREAT: Creates a new message queue if it does not already exist.
IPC_EXCL: Used with IPC_CREAT, it ensures that the call fails if the queue already exists.
Permission flags, like 0666 for read and write access for all users.
Return value:
On success, it returns a non-negative integer (the message queue identifier).
On failure, it returns -1 and sets errno.

	*/
	
	if(que == -1) {
		perror("Error while running msgget");
		return 0;
	}
	
	printf("Key: %d\n", msg_queue);
	printf("Message Queue ID: %d\n", que);
	
}
